spring:
  application:
    name: config-server

  output:
    ansi:
      enabled: always

  profiles:
    active: native, git

  cloud:
    config:
      server:
        native:
          search-locations: 'file:///Users/peter/Downloads/msa/project-configs'
        git:
          uri: https://github.com/peterkang98/project-configs.git
          default-label: main
          search-paths:
            - configs/*
            - configs
          basedir: configs
          clone-on-start: true

server:
  port: 3100

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3150/eureka/